version: "3.3"

services:
  server:
    build: .
    ports:
      - "1106:1337"
    image: secret
    environment:
      - FLAG=ISICTF{1m_n0t_4_s3cr3t_k33p3r}
    restart: always
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5