version: "3"

services:
  login-page:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./challenge/:/app
    ports:
      - 1421:80/tcp
    environment:
      - FLAG=ISICTF{4n07h3r_1nj3c710n_4nd_4n07h3r_fl46}
      - PASSWORD=uw8NWFyNSW0sAdKc0CLAJZ0D9r6zhmIu2jB7nNM