version: '3.3'

services:

  server:
    build: .
    ports:
      - 1200:8000
    image: crashme
    restart: always

    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          memory: 50M
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
