version: '3.3'

services:

  service:
    build: .
    ports:
      - 1104:22
    image: bashonly
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

