version: '3.3'

services:

  server:
    build: .
    ports:
      - 1201:1337
    restart: always
    image: deadbeef
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

