version: '3.3'

services:

  server:
    build: .
    ports:
      - 1202:1337
    image: ret2win
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

