version: "3.3"

services:
  server:
    build: .
    ports:
      - "1108:1337"
    image: yml
    restart: always
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5